version: '3.8'

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  notes-system_backend-develop:
    image: ${NEXUS_REG}/${SERVICE_NAME_BACKEND}
    container_name: ${SERVICE_NAME_BACKEND}
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      NODE_ENV: develop

  notes-system_frontend-develop:
    image: ${NEXUS_REG}/${SERVICE_NAME_FRONTEND}
    container_name: ${SERVICE_NAME_FRONTEND}
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - notes-system_backend-develop
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      NODE_ENV: develop

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter
      - cadvisor
      - postgres-exporter

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    restart: always
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "$DB_CONNECTION_URL"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
