# Generated by Django 5.1.6 on 2025-03-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='github',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='linkedin',
        ),
    ]
