# Generated by Django 5.2.1 on 2025-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_education_resume_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
