# Generated by Django 5.2.1 on 2025-05-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hobby',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='project',
            field=models.TextField(default='None', max_length=100),
        ),
    ]
