# Generated by Django 5.2.1 on 2025-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_hobby_resume_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='hobby',
            field=models.TextField(default='None', max_length=100),
        ),
    ]
