# Generated by Django 5.2.1 on 2025-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_alter_resume_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='hobby',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='project',
            field=models.TextField(default='None'),
        ),
    ]
