# Generated by Django 5.1.6 on 2025-04-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='short_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
