# Generated by Django 5.1.6 on 2025-05-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='media/pfp/default_pfp.webp', upload_to='media/pfp/'),
        ),
    ]
